
import shutil
import os

def save_diagrams():
    # Define source paths (Artifacts generated by the AI)
    # Note: These paths are specific to the artifacts generated in the previous step
    sources = {
        "HSV_Transform": r"C:/Users/Saiful Islam/.gemini/antigravity/brain/f2c7011a-82f2-43d5-bff4-552a10c31226/scientific_rgb_hsv_transform_1767911854532.png",
        "Pixel_Masking": r"C:/Users/Saiful Islam/.gemini/antigravity/brain/f2c7011a-82f2-43d5-bff4-552a10c31226/scientific_pixel_masking_1767911875324.png",
        "Anchor_Histogram": r"C:/Users/Saiful Islam/.gemini/antigravity/brain/f2c7011a-82f2-43d5-bff4-552a10c31226/scientific_anchor_histogram_1767911893700.png"
    }
    
    # Destination Directory
    dest_dir = r"f:\Test\cartilage_analysis_app\Methodology_Report"
    if not os.path.exists(dest_dir):
        os.makedirs(dest_dir)
        
    print(f"Saving images to: {dest_dir}")
    
    for name, src_path in sources.items():
        if os.path.exists(src_path):
            filename = f"Methodology_Figure_{name}.png"
            dest_path = os.path.join(dest_dir, filename)
            shutil.copy2(src_path, dest_path)
            print(f"Saved: {filename}")
        else:
            print(f"Error: Source file not found for {name} at {src_path}")

if __name__ == "__main__":
    save_diagrams()
